### ISSUE TITLE
Technical update asks from Rodney

### ISSUE THREAD

**Issue by setheliot** [setheliot/aws-well-architected-labs#3]
- [x] move to AWS Systems Manager parameter store for selecting the latest Amazon Linux 2 AMI instead of the mapping I have in the web server template.
- [x] move to AWS Secrets Manager for the database password (maybe even randomly generate one?)

Edit Sept 30 - I am splitting off the third item into its own item object (https://github.com/setheliot/aws-well-architected-labs/issues/20), so we can call this one DONE

**Comment by adhorn** [comment]
Getting the latest AMI is easily done within the WebApp lambda function.

**Comment by setheliot** [comment]
reviewed and merged: some action items here https://github.com/setheliot/aws-well-architected-labs/pull/19#pullrequestreview-295273311

**Comment by setheliot** [comment]
woot!
